### ISSUE TITLE
Copy edit

### ISSUE THREAD

**Issue by MissPhilbin** [raspberrypilearning/physical-computing-guide#1]
Hi @LornaLynch, would you mind giving this repo a once over testing the links too? Thanks.

**Comment by LornaLynch** [comment]
Will do. I'm without any childcare at the moment so it may take a little longer than nkormal, but I promise I'm on it!

**Comment by LornaLynch** [comment]
We still have Fritzing diagrams in connect-leds.md so we'll need Sam to do new-format circuit board images to replace these. 

There's also a Fritzing diagram (of the GPIO pins) in https://github.com/raspberrypilearning/physical-computing-guide/blob/master/gpio-plus-and-pi2.md

More Fritzing diagrams in https://github.com/raspberrypilearning/physical-computing-guide/blob/master/pull_up_down.md and https://github.com/raspberrypilearning/physical-computing-guide/blob/master/worksheet.md

**Comment by LornaLynch** [comment]
@MissPhilbin I've finished my check: I'd close the issue but didn't want to do this while the Fritzing diagrams are still there. Other than those, I think everything's ok (I've checked links etc)
