### ISSUE TITLE
Tech edit

### ISSUE THREAD

**Issue by MissPhilbin** [raspberrypilearning/physical-computing-guide#2]
Hi @mrichardson23 - Would you mind giving this resource a read and check I've not made any glaringly obvious mistakes. This is not my strong point. I've heavily "borrowed" from @clivebeale who knows much more than I about these things but I think he might be tied up with weather station atm. 

Thanks!

**Comment by mrichardson23** [comment]
Certainly! I'll work through it today.

**Comment by clivebeale** [comment]
Is there a resource testing afternoon tomorrow? I’ll take a look then if you want

clive

**Comment by MissPhilbin** [comment]
Thanks.
