### ISSUE TITLE
Cover Art

### ISSUE THREAD

**Issue by MissPhilbin** [raspberrypilearning/physical-computing-guide#3]
@samalderhyde - Here is a new resource requiring an illustration. As usual there is no hurry. The resource is a beginners guide to GPIO pins and components. Thanks.

**Comment by MissPhilbin** [comment]
@samalderhyde All Fritzing diagrams will also need to be replaced within this resource. Thank you.

**Comment by SteveAmor** [comment]
I have updated some of the Fritzing diagrams in PR #11 and a diagram in PR #8 
With all the other PRs I've raised, the text should now line up with the diagrams
